services:
  db:
    image: postgres:18.3-trixie
    container_name: openmu-postgres
    restart: always
    networks:
      - openmu-network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=${TIMEZ}
    volumes:
      - openmu-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  openmu:
    build:
      context: .
      dockerfile: Dockerfile
    image: openmu:latest
    container_name: openmu-server
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - openmu-network
    environment:
      - DB_HOST=db
      - DB_ADMIN_USER=${DB_USER}
      - DB_ADMIN_PW=${DB_PASS}
      - RESOLVE_IP=${RES_IP}
      - ASPNETCORE_URLS=http://+:8080
      - TZ=${TIMEZ}
    ports:
      - "55901:55901" # GameServer
      - "44405:44405" # ConnectServerGMO_client
      - "44406:44406" # ConnectServerOpenSource_client
      - "${ADM_PORT}:8080"   # Admin_Panel

networks:
  openmu-network:
    name: openmu-network
    driver: bridge

volumes:
  openmu-db-data:
    name: openmu-db
